import { Brand } from '@/types/store'

export const brands: Brand[] = [
  // === DEPORTIVAS / ATHLETIC ===
  { id: 'nike', nombre: 'Nike', slug: 'nike', descripcion: 'Ropa y calzado deportivo de alto rendimiento' },
  { id: 'adidas', nombre: 'Adidas', slug: 'adidas', descripcion: 'Moda deportiva y lifestyle' },
  { id: 'puma', nombre: 'Puma', slug: 'puma', descripcion: 'Calzado y ropa deportiva' },
  { id: 'reebok', nombre: 'Reebok', slug: 'reebok', descripcion: 'Calzado y ropa fitness' },
  { id: 'new-balance', nombre: 'New Balance', slug: 'new-balance', descripcion: 'Calzado deportivo y casual' },
  { id: 'under-armour', nombre: 'Under Armour', slug: 'under-armour', descripcion: 'Ropa de alto rendimiento' },
  { id: 'converse', nombre: 'Converse', slug: 'converse', descripcion: 'Icónicas zapatillas casual' },
  { id: 'vans', nombre: 'Vans', slug: 'vans', descripcion: 'Skate y streetwear' },
  { id: 'asics', nombre: 'ASICS', slug: 'asics', descripcion: 'Running y deporte' },
  { id: 'saucony', nombre: 'Saucony', slug: 'saucony', descripcion: 'Running de alto rendimiento' },
  { id: 'brooks', nombre: 'Brooks', slug: 'brooks', descripcion: 'Especialistas en running' },
  { id: 'on-running', nombre: 'On Running', slug: 'on-running', descripcion: 'Calzado running suizo' },
  { id: 'hoka', nombre: 'HOKA', slug: 'hoka', descripcion: 'Calzado running maximalista' },
  { id: 'mizuno', nombre: 'Mizuno', slug: 'mizuno', descripcion: 'Ropa y calzado deportivo japonés' },
  { id: 'fila', nombre: 'Fila', slug: 'fila', descripcion: 'Moda deportiva retro' },
  { id: 'champion', nombre: 'Champion', slug: 'champion', descripcion: 'Ropa deportiva clásica americana' },
  { id: 'columbia', nombre: 'Columbia', slug: 'columbia', descripcion: 'Ropa outdoor y aventura' },
  { id: 'the-north-face', nombre: 'The North Face', slug: 'the-north-face', descripcion: 'Outdoor y montaña' },
  { id: 'patagonia', nombre: 'Patagonia', slug: 'patagonia', descripcion: 'Outdoor sustentable' },
  { id: 'timberland', nombre: 'Timberland', slug: 'timberland', descripcion: 'Botas y ropa outdoor' },
  { id: 'jordan', nombre: 'Jordan', slug: 'jordan', descripcion: 'Calzado y ropa basketball' },
  { id: 'umbro', nombre: 'Umbro', slug: 'umbro', descripcion: 'Ropa y calzado fútbol' },
  { id: 'lotto', nombre: 'Lotto', slug: 'lotto', descripcion: 'Ropa deportiva italiana' },
  { id: 'kappa', nombre: 'Kappa', slug: 'kappa', descripcion: 'Ropa deportiva retro' },
  { id: 'kelme', nombre: 'Kelme', slug: 'kelme', descripcion: 'Calzado y ropa fútbol' },
  { id: 'joma', nombre: 'Joma', slug: 'joma', descripcion: 'Ropa deportiva española' },
  { id: 'penalty', nombre: 'Penalty', slug: 'penalty', descripcion: 'Ropa y calzado deportivo' },
  { id: 'babolat', nombre: 'Babolat', slug: 'babolat', descripcion: 'Equipamiento de tenis' },
  { id: 'wilson', nombre: 'Wilson', slug: 'wilson', descripcion: 'Equipamiento deportivo' },
  { id: 'head', nombre: 'Head', slug: 'head', descripcion: 'Ropa y equipo deportivo' },
  { id: 'yonex', nombre: 'Yonex', slug: 'yonex', descripcion: 'Bádminton y tenis' },
  { id: 'salomon', nombre: 'Salomon', slug: 'salomon', descripcion: 'Trail running y montaña' },
  { id: 'merrell', nombre: 'Merrell', slug: 'merrell', descripcion: 'Calzado outdoor y senderismo' },
  { id: 'keen', nombre: 'Keen', slug: 'keen', descripcion: 'Calzado outdoor' },
  { id: 'arc-teryx', nombre: "Arc'teryx", slug: 'arc-teryx', descripcion: 'Outdoor técnico premium' },
  { id: 'mammut', nombre: 'Mammut', slug: 'mammut', descripcion: 'Ropa de montaña suiza' },
  { id: 'karrimor', nombre: 'Karrimor', slug: 'karrimor', descripcion: 'Outdoor y senderismo' },
  { id: 'speedo', nombre: 'Speedo', slug: 'speedo', descripcion: 'Trajes de baño y natación' },
  { id: 'arena', nombre: 'Arena', slug: 'arena', descripcion: 'Ropa acuática competitiva' },
  { id: 'oakley', nombre: 'Oakley', slug: 'oakley', descripcion: 'Gafas y ropa deportiva' },
  { id: 'quiksilver', nombre: 'Quiksilver', slug: 'quiksilver', descripcion: 'Surf y deportes acuáticos' },
  { id: 'rip-curl', nombre: 'Rip Curl', slug: 'rip-curl', descripcion: 'Surf y playa' },
  { id: 'billabong', nombre: 'Billabong', slug: 'billabong', descripcion: 'Surf y playa' },
  { id: 'hurley', nombre: 'Hurley', slug: 'hurley', descripcion: 'Surf y streetwear' },
  { id: 'volcom', nombre: 'Volcom', slug: 'volcom', descripcion: 'Snowboard y surf' },

  // === MODA FAST FASHION ===
  { id: 'zara', nombre: 'Zara', slug: 'zara', descripcion: 'Moda rápida con estilo europeo' },
  { id: 'hm', nombre: 'H&M', slug: 'hm', descripcion: 'Moda accesible para toda la familia' },
  { id: 'pull-bear', nombre: 'Pull&Bear', slug: 'pull-bear', descripcion: 'Moda joven y urbana' },
  { id: 'bershka', nombre: 'Bershka', slug: 'bershka', descripcion: 'Tendencias para jóvenes' },
  { id: 'stradivarius', nombre: 'Stradivarius', slug: 'stradivarius', descripcion: 'Moda femenina joven' },
  { id: 'massimo-dutti', nombre: 'Massimo Dutti', slug: 'massimo-dutti', descripcion: 'Moda sofisticada' },
  { id: 'mango', nombre: 'Mango', slug: 'mango', descripcion: 'Moda femenina contemporánea' },
  { id: 'forever-21', nombre: 'Forever 21', slug: 'forever-21', descripcion: 'Moda accesible para jóvenes' },
  { id: 'shein', nombre: 'Shein', slug: 'shein', descripcion: 'Moda ultra accesible online' },
  { id: 'primark', nombre: 'Primark', slug: 'primark', descripcion: 'Moda económica irlandesa' },
  { id: 'uniqlo', nombre: 'Uniqlo', slug: 'uniqlo', descripcion: 'Básicos japoneses de calidad' },
  { id: 'gap', nombre: 'Gap', slug: 'gap', descripcion: 'Básicos americanos' },
  { id: 'old-navy', nombre: 'Old Navy', slug: 'old-navy', descripcion: 'Moda casual americana' },
  { id: 'banana-republic', nombre: 'Banana Republic', slug: 'banana-republic', descripcion: 'Moda casual premium' },
  { id: 'american-eagle', nombre: 'American Eagle', slug: 'american-eagle', descripcion: 'Jeans y casual americano' },
  { id: 'hollister', nombre: 'Hollister', slug: 'hollister', descripcion: 'Moda joven californiana' },
  { id: 'abercrombie', nombre: 'Abercrombie & Fitch', slug: 'abercrombie', descripcion: 'Moda casual premium americana' },
  { id: 'aeropostale', nombre: 'Aéropostale', slug: 'aeropostale', descripcion: 'Moda joven accesible' },
  { id: 'guess', nombre: 'Guess', slug: 'guess', descripcion: 'Moda y accesorios' },
  { id: 'calvin-klein', nombre: 'Calvin Klein', slug: 'calvin-klein', descripcion: 'Moda minimalista americana' },
  { id: 'tommy-hilfiger', nombre: 'Tommy Hilfiger', slug: 'tommy-hilfiger', descripcion: 'Estilo preppy americano' },
  { id: 'polo-ralph-lauren', nombre: 'Polo Ralph Lauren', slug: 'polo-ralph-lauren', descripcion: 'Estilo clásico americano premium' },
  { id: 'levis', nombre: "Levi's", slug: 'levis', descripcion: 'Jeans y denim clásicos' },
  { id: 'wrangler', nombre: 'Wrangler', slug: 'wrangler', descripcion: 'Jeans y ropa vaquera' },
  { id: 'lee', nombre: 'Lee', slug: 'lee', descripcion: 'Jeans clásicos americanos' },
  { id: 'diesel', nombre: 'Diesel', slug: 'diesel', descripcion: 'Denim premium italiano' },
  { id: 'pepe-jeans', nombre: 'Pepe Jeans', slug: 'pepe-jeans', descripcion: 'Denim y casual europeo' },
  { id: 'dockers', nombre: 'Dockers', slug: 'dockers', descripcion: 'Pantalones casual clásicos' },
  { id: 'nautica', nombre: 'Nautica', slug: 'nautica', descripcion: 'Moda náutica casual' },
  { id: 'columbia-sportswear', nombre: 'Columbia Sportswear', slug: 'columbia-sportswear', descripcion: 'Ropa outdoor americana' },

  // === LUJO Y PREMIUM ===
  { id: 'louis-vuitton', nombre: 'Louis Vuitton', slug: 'louis-vuitton', descripcion: 'Lujo francés icónico' },
  { id: 'gucci', nombre: 'Gucci', slug: 'gucci', descripcion: 'Moda italiana de lujo' },
  { id: 'prada', nombre: 'Prada', slug: 'prada', descripcion: 'Lujo italiano minimalista' },
  { id: 'chanel', nombre: 'Chanel', slug: 'chanel', descripcion: 'Alta costura francesa' },
  { id: 'hermes', nombre: 'Hermès', slug: 'hermes', descripcion: 'Lujo francés artesanal' },
  { id: 'dior', nombre: 'Dior', slug: 'dior', descripcion: 'Alta moda francesa' },
  { id: 'versace', nombre: 'Versace', slug: 'versace', descripcion: 'Lujo italiano extravagante' },
  { id: 'armani', nombre: 'Giorgio Armani', slug: 'armani', descripcion: 'Elegancia italiana' },
  { id: 'burberry', nombre: 'Burberry', slug: 'burberry', descripcion: 'Lujo británico clásico' },
  { id: 'fendi', nombre: 'Fendi', slug: 'fendi', descripcion: 'Piel y lujo romano' },
  { id: 'balenciaga', nombre: 'Balenciaga', slug: 'balenciaga', descripcion: 'Lujo avant-garde' },
  { id: 'valentino', nombre: 'Valentino', slug: 'valentino', descripcion: 'Alta costura italiana' },
  { id: 'saint-laurent', nombre: 'Saint Laurent', slug: 'saint-laurent', descripcion: 'Rock chic parisino' },
  { id: 'bottega-veneta', nombre: 'Bottega Veneta', slug: 'bottega-veneta', descripcion: 'Artesanía italiana de lujo' },
  { id: 'off-white', nombre: 'Off-White', slug: 'off-white', descripcion: 'Streetwear de lujo' },
  { id: 'givenchy', nombre: 'Givenchy', slug: 'givenchy', descripcion: 'Elegancia parisina' },
  { id: 'balmain', nombre: 'Balmain', slug: 'balmain', descripcion: 'Alta costura parisina' },
  { id: 'celine', nombre: 'Céline', slug: 'celine', descripcion: 'Minimalismo francés de lujo' },
  { id: 'loewe', nombre: 'Loewe', slug: 'loewe', descripcion: 'Lujo español artesanal' },
  { id: 'moncler', nombre: 'Moncler', slug: 'moncler', descripcion: 'Abrigos de lujo' },
  { id: 'tod-s', nombre: "Tod's", slug: 'tod-s', descripcion: 'Calzado italiano artesanal' },
  { id: 'ferragamo', nombre: 'Ferragamo', slug: 'ferragamo', descripcion: 'Calzado italiano de lujo' },
  { id: 'jimmy-choo', nombre: 'Jimmy Choo', slug: 'jimmy-choo', descripcion: 'Calzado de lujo femenino' },
  { id: 'manolo-blahnik', nombre: 'Manolo Blahnik', slug: 'manolo-blahnik', descripcion: 'Zapatos de lujo icónicos' },
  { id: 'louboutin', nombre: 'Christian Louboutin', slug: 'louboutin', descripcion: 'Zapatos de suela roja' },
  { id: 'mcqueen', nombre: 'Alexander McQueen', slug: 'mcqueen', descripcion: 'Alta costura dramática' },
  { id: 'stella-mccartney', nombre: 'Stella McCartney', slug: 'stella-mccartney', descripcion: 'Lujo sustentable' },
  { id: 'vivienne-westwood', nombre: 'Vivienne Westwood', slug: 'vivienne-westwood', descripcion: 'Punk y alta costura' },
  { id: 'acne-studios', nombre: 'Acne Studios', slug: 'acne-studios', descripcion: 'Moda escandinava premium' },
  { id: 'marni', nombre: 'Marni', slug: 'marni', descripcion: 'Moda italiana ecléctica' },
  { id: 'kenzo', nombre: 'Kenzo', slug: 'kenzo', descripcion: 'Moda franco-japonesa' },
  { id: 'lanvin', nombre: 'Lanvin', slug: 'lanvin', descripcion: 'Elegancia parisina' },
  { id: 'moschino', nombre: 'Moschino', slug: 'moschino', descripcion: 'Moda italiana irreverente' },
  { id: 'dsquared2', nombre: 'Dsquared2', slug: 'dsquared2', descripcion: 'Denim de lujo canadiense-italiano' },
  { id: 'philipp-plein', nombre: 'Philipp Plein', slug: 'philipp-plein', descripcion: 'Lujo extravagante alemán' },
  { id: 'lacoste', nombre: 'Lacoste', slug: 'lacoste', descripcion: 'Elegancia deportiva francesa' },
  { id: 'hugo-boss', nombre: 'Hugo Boss', slug: 'hugo-boss', descripcion: 'Moda formal y casual alemana' },
  { id: 'michael-kors', nombre: 'Michael Kors', slug: 'michael-kors', descripcion: 'Accesorios y moda americana' },
  { id: 'coach', nombre: 'Coach', slug: 'coach', descripcion: 'Accesorios de piel americanos' },
  { id: 'kate-spade', nombre: 'Kate Spade', slug: 'kate-spade', descripcion: 'Bolsas y accesorios femeninos' },
  { id: 'tory-burch', nombre: 'Tory Burch', slug: 'tory-burch', descripcion: 'Moda americana preppy' },
  { id: 'marc-jacobs', nombre: 'Marc Jacobs', slug: 'marc-jacobs', descripcion: 'Moda americana excéntrica' },
  { id: 'versace-jeans', nombre: 'Versace Jeans Couture', slug: 'versace-jeans', descripcion: 'Denim de lujo italiano' },
  { id: 'emporio-armani', nombre: 'Emporio Armani', slug: 'emporio-armani', descripcion: 'Línea joven de Armani' },
  { id: 'armani-exchange', nombre: 'Armani Exchange', slug: 'armani-exchange', descripcion: 'Casual de Armani' },
  { id: 'dolce-gabbana', nombre: 'Dolce & Gabbana', slug: 'dolce-gabbana', descripcion: 'Lujo exuberante italiano' },
  { id: 'roberto-cavalli', nombre: 'Roberto Cavalli', slug: 'roberto-cavalli', descripcion: 'Moda italiana animal print' },
  { id: 'isabel-marant', nombre: 'Isabel Marant', slug: 'isabel-marant', descripcion: 'Boho chic parisino' },
  { id: 'sandro', nombre: 'Sandro', slug: 'sandro', descripcion: 'Moda francesa contemporánea' },
  { id: 'maje', nombre: 'Maje', slug: 'maje', descripcion: 'Moda femenina francesa' },

  // === STREETWEAR Y URBAN ===
  { id: 'supreme', nombre: 'Supreme', slug: 'supreme', descripcion: 'Skateboarding streetwear icónico' },
  { id: 'palace', nombre: 'Palace', slug: 'palace', descripcion: 'Streetwear skate británico' },
  { id: 'stussy', nombre: 'Stüssy', slug: 'stussy', descripcion: 'Streetwear surf californiano' },
  { id: 'carhartt-wip', nombre: 'Carhartt WIP', slug: 'carhartt-wip', descripcion: 'Workwear streetwear' },
  { id: 'dickies', nombre: 'Dickies', slug: 'dickies', descripcion: 'Workwear y streetwear' },
  { id: 'huf', nombre: 'HUF', slug: 'huf', descripcion: 'Skate y streetwear californiano' },
  { id: 'thrasher', nombre: 'Thrasher', slug: 'thrasher', descripcion: 'Skateboarding magazine brand' },
  { id: 'anti-social-social-club', nombre: 'Anti Social Social Club', slug: 'anti-social-social-club', descripcion: 'Streetwear cult' },
  { id: 'kith', nombre: 'Kith', slug: 'kith', descripcion: 'Streetwear premium NY' },
  { id: 'fear-of-god', nombre: 'Fear of God', slug: 'fear-of-god', descripcion: 'Lujo streetwear californiano' },
  { id: 'essentials', nombre: 'Essentials (FOG)', slug: 'essentials', descripcion: 'Streetwear accesible de Fear of God' },
  { id: 'human-made', nombre: 'Human Made', slug: 'human-made', descripcion: 'Streetwear japonés de Nigo' },
  { id: 'bape', nombre: 'A Bathing Ape (BAPE)', slug: 'bape', descripcion: 'Streetwear japonés icónico' },
  { id: 'palace-skateboards', nombre: 'Palace Skateboards', slug: 'palace-skateboards', descripcion: 'Skate streetwear UK' },
  { id: 'noah', nombre: 'Noah NYC', slug: 'noah', descripcion: 'Streetwear NY con consciencia' },
  { id: 'pleasures', nombre: 'Pleasures', slug: 'pleasures', descripcion: 'Streetwear LA con actitud' },
  { id: 'golf-wang', nombre: 'Golf Wang', slug: 'golf-wang', descripcion: 'Streetwear de Tyler the Creator' },
  { id: 'rhude', nombre: 'Rhude', slug: 'rhude', descripcion: 'Streetwear de lujo californiano' },
  { id: 'amiri', nombre: 'Amiri', slug: 'amiri', descripcion: 'Lujo rock streetwear LA' },
  { id: 'represent', nombre: 'Represent', slug: 'represent', descripcion: 'Streetwear premium británico' },
  { id: 'trapstar', nombre: 'Trapstar', slug: 'trapstar', descripcion: 'Streetwear urbano londinense' },
  { id: 'corteiz', nombre: 'Corteiz', slug: 'corteiz', descripcion: 'Streetwear underground UK' },
  { id: 'daily-paper', nombre: 'Daily Paper', slug: 'daily-paper', descripcion: 'Streetwear afro-europeo' },

  // === MARCAS MEXICANAS ===
  { id: 'rebook-mx', nombre: 'Capa de Ozono', slug: 'capa-de-ozono', descripcion: 'Marca mexicana de moda urbana' },
  { id: 'el-palacio', nombre: 'El Palacio de Hierro', slug: 'palacio-de-hierro', descripcion: 'Tienda departamental mexicana premium' },
  { id: 'Andrea', nombre: 'Andrea', slug: 'andrea', descripcion: 'Calzado y moda mexicana por catálogo' },
  { id: 'price-shoes', nombre: 'Price Shoes', slug: 'price-shoes', descripcion: 'Calzado y moda mexicana' },
  { id: 'de-acero', nombre: 'De Acero', slug: 'de-acero', descripcion: 'Calzado industrial mexicano' },
  { id: 'flexi', nombre: 'Flexi', slug: 'flexi', descripcion: 'Calzado de cuero mexicano' },
  { id: 'bata', nombre: 'Bata', slug: 'bata', descripcion: 'Calzado accesible con presencia en México' },
  { id: 'canadá', nombre: 'Canadá', slug: 'canada', descripcion: 'Botas vaqueras mexicanas' },
  { id: 'emyco', nombre: 'Emyco', slug: 'emyco', descripcion: 'Calzado femenino mexicano' },
  { id: 'panam', nombre: 'Panam', slug: 'panam', descripcion: 'Tenis mexicanos icónicos' },
  { id: 'cinderella', nombre: 'Cinderella', slug: 'cinderella', descripcion: 'Calzado femenino mexicano' },
  { id: 'aparoni', nombre: 'Aparoni', slug: 'aparoni', descripcion: 'Moda mexicana contemporánea' },
  { id: 'coconut', nombre: 'Coconut', slug: 'coconut', descripcion: 'Ropa casual mexicana' },
  { id: 'suburbia', nombre: 'Suburbia', slug: 'suburbia', descripcion: 'Tienda de moda para familia mexicana' },
  { id: 'sears-mx', nombre: 'Sears México', slug: 'sears-mx', descripcion: 'Tienda departamental en México' },
  { id: 'bodega-aurrera', nombre: 'Bodega Aurrerá', slug: 'bodega-aurrera', descripcion: 'Ropa accesible Walmart México' },
  { id: 'chedraui', nombre: 'Chedraui', slug: 'chedraui', descripcion: 'Supermercado con sección de ropa' },
  { id: 'soriana', nombre: 'Soriana', slug: 'soriana', descripcion: 'Supermercado con sección de ropa' },
  { id: 'lob', nombre: 'LOB', slug: 'lob', descripcion: 'Moda femenina mexicana' },
  { id: 'cklass', nombre: 'Cklass', slug: 'cklass', descripcion: 'Moda femenina mexicana por catálogo' },
  { id: 'vans-mx', nombre: 'Vans México', slug: 'vans-mx', descripcion: 'Vans oficial en México' },
  { id: 'portos', nombre: 'Portos', slug: 'portos', descripcion: 'Zapaterías mexicanas' },
  { id: 'marti', nombre: 'Martí', slug: 'marti', descripcion: 'Tienda de deportes mexicana' },
  { id: 'deportes-charly', nombre: 'Charly', slug: 'charly', descripcion: 'Calzado y uniforme deportivo mexicano' },
  { id: 'terra', nombre: 'Terra', slug: 'terra', descripcion: 'Botas y calzado mexicano' },
  { id: 'rocky', nombre: 'Rocky', slug: 'rocky', descripcion: 'Calzado industrial mexicano' },
  { id: 'azaleia', nombre: 'Azaleia', slug: 'azaleia', descripcion: 'Calzado femenino brasileño en México' },
  { id: 'brantano', nombre: 'Brantano', slug: 'brantano', descripcion: 'Zapaterías en México' },
  { id: 'regatta', nombre: 'Regatta', slug: 'regatta', descripcion: 'Ropa outdoor en México' },
  { id: 'oxxo-moda', nombre: 'OXXO Moda', slug: 'oxxo-moda', descripcion: 'Accesorios y básicos en tiendas OXXO' },

  // === TIENDAS DEPARTAMENTALES / MARKETPLACES ===
  { id: 'liverpool', nombre: 'Liverpool', slug: 'liverpool', descripcion: 'Tienda departamental mexicana premium' },
  { id: 'amazon-mx', nombre: 'Amazon México', slug: 'amazon-mx', descripcion: 'Marketplace con envío rápido' },
  { id: 'mercado-libre', nombre: 'Mercado Libre', slug: 'mercado-libre', descripcion: 'Marketplace líder en México' },
  { id: 'coppel', nombre: 'Coppel', slug: 'coppel', descripcion: 'Tienda departamental accesible' },
  { id: 'walmart-mx', nombre: 'Walmart México', slug: 'walmart-mx', descripcion: 'Supermercado con ropa accesible' },
  { id: 'fashion-pass', nombre: 'Fashion Pass', slug: 'fashion-pass', descripcion: 'E-commerce de moda en México' },
  { id: 'privalia', nombre: 'Privalia', slug: 'privalia', descripcion: 'Club de ventas online de moda' },
  { id: 'logistik', nombre: 'Logistik', slug: 'logistik', descripcion: 'Ropa deportiva en México' },
  { id: 'innovasport', nombre: 'Innovasport', slug: 'innovasport', descripcion: 'Tienda de deportes premium en México' },
  { id: 'nike-factory', nombre: 'Nike Factory Store', slug: 'nike-factory', descripcion: 'Outlet oficial Nike' },
  { id: 'adidas-outlet', nombre: 'Adidas Outlet', slug: 'adidas-outlet', descripcion: 'Outlet oficial Adidas' },

  // === MODA FEMENINA ===
  { id: 'diane-von-furstenberg', nombre: 'Diane von Furstenberg', slug: 'dvf', descripcion: 'Moda femenina icónica' },
  { id: 'bcbg', nombre: 'BCBG Max Azria', slug: 'bcbg', descripcion: 'Moda femenina contemporánea' },
  { id: 'alice-olivia', nombre: 'Alice + Olivia', slug: 'alice-olivia', descripcion: 'Moda femenina playful' },
  { id: 'free-people', nombre: 'Free People', slug: 'free-people', descripcion: 'Moda boho femenina' },
  { id: 'anthropologie', nombre: 'Anthropologie', slug: 'anthropologie', descripcion: 'Moda y estilo de vida bohemio' },
  { id: 'reformation', nombre: 'Reformation', slug: 'reformation', descripcion: 'Moda femenina sustentable' },
  { id: 'aritzia', nombre: 'Aritzia', slug: 'aritzia', descripcion: 'Moda femenina canadiense' },
  { id: 'ann-taylor', nombre: 'Ann Taylor', slug: 'ann-taylor', descripcion: 'Moda femenina profesional americana' },
  { id: 'white-house-black-market', nombre: 'White House Black Market', slug: 'whbm', descripcion: 'Moda femenina sofisticada' },
  { id: 'loft', nombre: 'LOFT', slug: 'loft', descripcion: 'Moda femenina casual sofisticada' },
  { id: 'j-crew', nombre: 'J.Crew', slug: 'j-crew', descripcion: 'Estilo preppy americano' },
  { id: 'brooks-brothers', nombre: 'Brooks Brothers', slug: 'brooks-brothers', descripcion: 'Clásico americano formal' },
  { id: 'ted-baker', nombre: 'Ted Baker', slug: 'ted-baker', descripcion: 'Moda británica contemporánea' },
  { id: 'reiss', nombre: 'Reiss', slug: 'reiss', descripcion: 'Moda premium británica' },
  { id: 'cos', nombre: 'COS', slug: 'cos', descripcion: 'Moda minimalista de H&M' },
  { id: 'arket', nombre: 'Arket', slug: 'arket', descripcion: 'Moda escandinava atemporal' },
  { id: 'monki', nombre: 'Monki', slug: 'monki', descripcion: 'Moda joven escandinava' },
  { id: 'weekday', nombre: 'Weekday', slug: 'weekday', descripcion: 'Denim y moda escandinava' },
  { id: '& other stories', nombre: '& Other Stories', slug: 'other-stories', descripcion: 'Moda creativa escandinava' },
  { id: 'vila', nombre: 'Vila Clothes', slug: 'vila', descripcion: 'Moda femenina escandinava accesible' },
  { id: 'vero-moda', nombre: 'Vero Moda', slug: 'vero-moda', descripcion: 'Moda femenina danesa' },
  { id: 'only', nombre: 'Only', slug: 'only', descripcion: 'Moda joven femenina' },
  { id: 'esprit', nombre: 'Esprit', slug: 'esprit', descripcion: 'Moda casual internacional' },
  { id: 'mexx', nombre: 'Mexx', slug: 'mexx', descripcion: 'Moda holandesa casual' },
  { id: 'liu-jo', nombre: 'Liu Jo', slug: 'liu-jo', descripcion: 'Moda femenina italiana' },
  { id: 'pinko', nombre: 'Pinko', slug: 'pinko', descripcion: 'Moda italiana femenina chic' },
  { id: 'elisabetta-franchi', nombre: 'Elisabetta Franchi', slug: 'elisabetta-franchi', descripcion: 'Moda italiana glamurosa' },
  { id: 'patrizia-pepe', nombre: 'Patrizia Pepe', slug: 'patrizia-pepe', descripcion: 'Moda italiana contemporánea' },
  { id: 'max-mara', nombre: 'Max Mara', slug: 'max-mara', descripcion: 'Elegancia italiana intemporal' },
  { id: 'marella', nombre: 'Marella', slug: 'marella', descripcion: 'Línea casual de Max Mara' },
  { id: 'weekday-se', nombre: 'Acne Studios', slug: 'acne', descripcion: 'Moda escandinava de autor' },
  { id: 'ganni', nombre: 'Ganni', slug: 'ganni', descripcion: 'Moda danesa contemporánea' },
  { id: 'rotate', nombre: 'Rotate', slug: 'rotate', descripcion: 'Party wear danés' },
  { id: 'stand-studio', nombre: 'Stand Studio', slug: 'stand-studio', descripcion: 'Abrigos escandinavos premium' },

  // === CALZADO ===
  { id: 'dr-martens', nombre: 'Dr. Martens', slug: 'dr-martens', descripcion: 'Botas icónicas británicas' },
  { id: 'ugg', nombre: 'UGG', slug: 'ugg', descripcion: 'Botas de borrego australianas' },
  { id: 'skechers', nombre: 'Skechers', slug: 'skechers', descripcion: 'Calzado cómodo y casual' },
  { id: 'clarks', nombre: 'Clarks', slug: 'clarks', descripcion: 'Calzado británico clásico' },
  { id: 'ecco', nombre: 'Ecco', slug: 'ecco', descripcion: 'Calzado danés de calidad' },
  { id: 'geox', nombre: 'Geox', slug: 'geox', descripcion: 'Calzado transpirable italiano' },
  { id: 'birkenstock', nombre: 'Birkenstock', slug: 'birkenstock', descripcion: 'Sandalias alemanas ergonómicas' },
  { id: 'crocs', nombre: 'Crocs', slug: 'crocs', descripcion: 'Calzado de EVA colorido' },
  { id: 'havaianas', nombre: 'Havaianas', slug: 'havaianas', descripcion: 'Sandalias brasileñas icónicas' },
  { id: 'reef', nombre: 'Reef', slug: 'reef', descripcion: 'Sandalias de surf' },
  { id: 'toms', nombre: 'TOMS', slug: 'toms', descripcion: 'Alpargatas con causa social' },
  { id: 'superga', nombre: 'Superga', slug: 'superga', descripcion: 'Tenis italianos clásicos' },
  { id: 'keds', nombre: 'Keds', slug: 'keds', descripcion: 'Tenis casuales americanos' },
  { id: 'sperry', nombre: 'Sperry', slug: 'sperry', descripcion: 'Calzado náutico americano' },
  { id: 'wolverine', nombre: 'Wolverine', slug: 'wolverine', descripcion: 'Botas de trabajo americanas' },
  { id: 'red-wing', nombre: 'Red Wing', slug: 'red-wing', descripcion: 'Botas artesanales americanas' },
  { id: 'thursday-boots', nombre: 'Thursday Boot Co.', slug: 'thursday-boots', descripcion: 'Botas de cuero premium' },
  { id: 'allen-edmonds', nombre: 'Allen Edmonds', slug: 'allen-edmonds', descripcion: 'Zapatos de vestir americanos' },
  { id: 'cole-haan', nombre: 'Cole Haan', slug: 'cole-haan', descripcion: 'Calzado de vestir cómodo' },
  { id: 'johnston-murphy', nombre: 'Johnston & Murphy', slug: 'johnston-murphy', descripcion: 'Calzado clásico americano' },
  { id: 'steve-madden', nombre: 'Steve Madden', slug: 'steve-madden', descripcion: 'Moda en calzado accesible' },
  { id: 'aldo', nombre: 'Aldo', slug: 'aldo', descripcion: 'Calzado y accesorios canadienses' },
  { id: 'nine-west', nombre: 'Nine West', slug: 'nine-west', descripcion: 'Calzado femenino de moda' },
  { id: 'naturalizer', nombre: 'Naturalizer', slug: 'naturalizer', descripcion: 'Calzado femenino cómodo' },
  { id: 'sam-edelman', nombre: 'Sam Edelman', slug: 'sam-edelman', descripcion: 'Calzado femenino tendencia' },
  { id: 'franco-sarto', nombre: 'Franco Sarto', slug: 'franco-sarto', descripcion: 'Calzado femenino italiano-americano' },
  { id: 'aerosoles', nombre: 'Aerosoles', slug: 'aerosoles', descripcion: 'Calzado cómodo femenino' },
  { id: 'born', nombre: "Born", slug: 'born', descripcion: 'Calzado artesanal cómodo' },
  { id: 'dansko', nombre: 'Dansko', slug: 'dansko', descripcion: 'Zuecos daneses ergonómicos' },
  { id: 'keen-footwear', nombre: 'Keen Footwear', slug: 'keen-footwear', descripcion: 'Calzado outdoor híbrido' },
  { id: 'palladium', nombre: 'Palladium', slug: 'palladium', descripcion: 'Boots urbanos franceses' },
  { id: 'sorel', nombre: 'Sorel', slug: 'sorel', descripcion: 'Botas de invierno canadienses' },

  // === ROPA INTERIOR Y BÁSICOS ===
  { id: 'victorias-secret', nombre: "Victoria's Secret", slug: 'victorias-secret', descripcion: 'Lencería y ropa íntima' },
  { id: 'pink', nombre: 'PINK (VS)', slug: 'pink', descripcion: 'Ropa casual y lencería juvenil' },
  { id: 'hanes', nombre: 'Hanes', slug: 'hanes', descripcion: 'Ropa interior y básicos' },
  { id: 'fruit-of-the-loom', nombre: 'Fruit of the Loom', slug: 'fruit-of-the-loom', descripcion: 'Ropa interior básica' },
  { id: 'gildan', nombre: 'Gildan', slug: 'gildan', descripcion: 'Playeras y básicos' },
  { id: 'calvin-klein-underwear', nombre: 'Calvin Klein Underwear', slug: 'ck-underwear', descripcion: 'Ropa interior premium' },
  { id: 'tommy-john', nombre: 'Tommy John', slug: 'tommy-john', descripcion: 'Ropa interior masculina premium' },
  { id: 'saxx', nombre: 'SAXX', slug: 'saxx', descripcion: 'Ropa interior masculina cómoda' },
  { id: 'mey', nombre: 'MEY', slug: 'mey', descripcion: 'Ropa interior alemana de lujo' },
  { id: 'triumph', nombre: 'Triumph', slug: 'triumph', descripcion: 'Lencería europea' },
  { id: 'playtex', nombre: 'Playtex', slug: 'playtex', descripcion: 'Lencería cómoda' },
  { id: 'wonderbra', nombre: 'Wonderbra', slug: 'wonderbra', descripcion: 'Brassieres con soporte' },
  { id: 'maidenform', nombre: 'Maidenform', slug: 'maidenform', descripcion: 'Brassieres americanos' },
  { id: 'wacoal', nombre: 'Wacoal', slug: 'wacoal', descripcion: 'Lencería japonesa premium' },
  { id: 'hanky-panky', nombre: 'Hanky Panky', slug: 'hanky-panky', descripcion: 'Lencería femenina NY' },
  { id: 'commando', nombre: 'Commando', slug: 'commando', descripcion: 'Lencería sin costuras' },
  { id: 'skims', nombre: 'SKIMS', slug: 'skims', descripcion: 'Shapewear de Kim Kardashian' },
  { id: 'spanx', nombre: 'Spanx', slug: 'spanx', descripcion: 'Shapewear y básicos cómodos' },
  { id: 'aerie', nombre: 'Aerie', slug: 'aerie', descripcion: 'Lencería y ropa cómoda de AE' },

  // === ACTIVEWEAR / ATHLEISURE ===
  { id: 'lululemon', nombre: 'Lululemon', slug: 'lululemon', descripcion: 'Ropa de yoga y athletic premium' },
  { id: 'gymshark', nombre: 'Gymshark', slug: 'gymshark', descripcion: 'Ropa de gym británica' },
  { id: 'fabletics', nombre: 'Fabletics', slug: 'fabletics', descripcion: 'Ropa deportiva por suscripción' },
  { id: 'vuori', nombre: 'Vuori', slug: 'vuori', descripcion: 'Athleisure premium californiano' },
  { id: 'alo-yoga', nombre: 'Alo Yoga', slug: 'alo-yoga', descripcion: 'Ropa yoga premium LA' },
  { id: 'outdoor-voices', nombre: 'Outdoor Voices', slug: 'outdoor-voices', descripcion: 'Activewear casual' },
  { id: 'sweaty-betty', nombre: 'Sweaty Betty', slug: 'sweaty-betty', descripcion: 'Activewear femenino británico' },
  { id: 'athleta', nombre: 'Athleta', slug: 'athleta', descripcion: 'Activewear femenino de Gap' },
  { id: 'title-nine', nombre: 'Title Nine', slug: 'title-nine', descripcion: 'Activewear femenino' },
  { id: 'bandier', nombre: 'Bandier', slug: 'bandier', descripcion: 'Activewear premium multi-marca' },
  { id: 'splits59', nombre: 'Splits59', slug: 'splits59', descripcion: 'Activewear yoga LA' },
  { id: 'beyond-yoga', nombre: 'Beyond Yoga', slug: 'beyond-yoga', descripcion: 'Yoga wear premium suave' },
  { id: 'p90x', nombre: 'Beachbody', slug: 'beachbody', descripcion: 'Ropa fitness americana' },
  { id: 'ex-officio', nombre: 'ExOfficio', slug: 'ex-officio', descripcion: 'Ropa de viaje técnica' },
  { id: 'primal-wear', nombre: 'Primal Wear', slug: 'primal-wear', descripcion: 'Ropa ciclismo' },
  { id: 'pearl-izumi', nombre: 'Pearl Izumi', slug: 'pearl-izumi', descripcion: 'Ropa ciclismo y running' },
  { id: 'castelli', nombre: 'Castelli', slug: 'castelli', descripcion: 'Ropa ciclismo italiana premium' },
  { id: 'rapha', nombre: 'Rapha', slug: 'rapha', descripcion: 'Ropa ciclismo premium UK' },
  { id: 'icebreaker', nombre: 'Icebreaker', slug: 'icebreaker', descripcion: 'Ropa merino neozelandesa' },
  { id: 'smartwool', nombre: 'Smartwool', slug: 'smartwool', descripcion: 'Ropa y calcetines de lana merino' },
  { id: 'darn-tough', nombre: 'Darn Tough', slug: 'darn-tough', descripcion: 'Calcetines merino Vermont' },

  // === NIÑOS Y BEBÉS ===
  { id: 'carter-s', nombre: "Carter's", slug: 'carters', descripcion: 'Ropa infantil americana' },
  { id: 'oshkosh', nombre: "OshKosh B'gosh", slug: 'oshkosh', descripcion: 'Ropa infantil clásica americana' },
  { id: 'gerber-childrenswear', nombre: 'Gerber Childrenswear', slug: 'gerber', descripcion: 'Ropa de bebé' },
  { id: 'gymboree', nombre: 'Gymboree', slug: 'gymboree', descripcion: 'Ropa infantil colorida' },
  { id: 'children-s-place', nombre: "The Children's Place", slug: 'childrens-place', descripcion: 'Ropa infantil accesible' },
  { id: 'hanna-andersson', nombre: 'Hanna Andersson', slug: 'hanna-andersson', descripcion: 'Ropa infantil escandinava' },
  { id: 'mini-boden', nombre: 'Mini Boden', slug: 'mini-boden', descripcion: 'Ropa infantil británica divertida' },
  { id: 'zara-kids', nombre: 'Zara Kids', slug: 'zara-kids', descripcion: 'Moda infantil de Zara' },
  { id: 'hm-kids', nombre: 'H&M Kids', slug: 'hm-kids', descripcion: 'Ropa infantil de H&M' },
  { id: 'gap-kids', nombre: 'GapKids', slug: 'gap-kids', descripcion: 'Ropa infantil americana' },
  { id: 'petit-bateau', nombre: 'Petit Bateau', slug: 'petit-bateau', descripcion: 'Ropa infantil francesa premium' },
  { id: 'bonpoint', nombre: 'Bonpoint', slug: 'bonpoint', descripcion: 'Ropa infantil francesa de lujo' },
  { id: 'burberry-kids', nombre: 'Burberry Kids', slug: 'burberry-kids', descripcion: 'Ropa infantil de Burberry' },
  { id: 'gucci-kids', nombre: 'Gucci Kids', slug: 'gucci-kids', descripcion: 'Ropa infantil de lujo' },
  { id: 'moschino-kids', nombre: 'Moschino Kids', slug: 'moschino-kids', descripcion: 'Ropa infantil italiana divertida' },
  { id: 'versace-kids', nombre: 'Young Versace', slug: 'versace-kids', descripcion: 'Ropa infantil de Versace' },

  // === ACCESORIOS Y COMPLEMENTOS ===
  { id: 'ray-ban', nombre: 'Ray-Ban', slug: 'ray-ban', descripcion: 'Gafas de sol icónicas' },
  { id: 'persol', nombre: 'Persol', slug: 'persol', descripcion: 'Gafas italianas artesanales' },
  { id: 'carrera', nombre: 'Carrera', slug: 'carrera', descripcion: 'Gafas deportivas icónicas' },
  { id: 'maui-jim', nombre: 'Maui Jim', slug: 'maui-jim', descripcion: 'Gafas de sol premium hawaianas' },
  { id: 'costa', nombre: 'Costa Del Mar', slug: 'costa', descripcion: 'Gafas de sol para pesca' },
  { id: 'swatch', nombre: 'Swatch', slug: 'swatch', descripcion: 'Relojes suizos coloridos' },
  { id: 'casio', nombre: 'Casio', slug: 'casio', descripcion: 'Relojes japoneses resistentes' },
  { id: 'fossil', nombre: 'Fossil', slug: 'fossil', descripcion: 'Relojes y accesorios de moda' },
  { id: 'timex', nombre: 'Timex', slug: 'timex', descripcion: 'Relojes americanos clásicos' },
  { id: 'nixon', nombre: 'Nixon', slug: 'nixon', descripcion: 'Relojes y accesorios de surf' },
  { id: 'mvmt', nombre: 'MVMT', slug: 'mvmt', descripcion: 'Relojes minimalistas americanos' },
  { id: 'invicta', nombre: 'Invicta', slug: 'invicta', descripcion: 'Relojes llamativos accesibles' },
  { id: 'herschel', nombre: 'Herschel Supply Co.', slug: 'herschel', descripcion: 'Mochilas y accesorios canadienses' },
  { id: 'eastpak', nombre: 'Eastpak', slug: 'eastpak', descripcion: 'Mochilas duraderas belgas' },
  { id: 'jansport', nombre: 'JanSport', slug: 'jansport', descripcion: 'Mochilas americanas clásicas' },
  { id: 'osprey', nombre: 'Osprey', slug: 'osprey', descripcion: 'Mochilas de trekking premium' },
  { id: 'deuter', nombre: 'Deuter', slug: 'deuter', descripcion: 'Mochilas alemanas de montaña' },
  { id: 'gregory', nombre: 'Gregory', slug: 'gregory', descripcion: 'Mochilas de montaña premium' },
  { id: 'tumi', nombre: 'Tumi', slug: 'tumi', descripcion: 'Maletas y mochilas de viaje premium' },
  { id: 'samsonite', nombre: 'Samsonite', slug: 'samsonite', descripcion: 'Maletas de viaje' },
  { id: 'away', nombre: 'Away', slug: 'away', descripcion: 'Maletas modernas con cargador' },
  { id: 'rimowa', nombre: 'RIMOWA', slug: 'rimowa', descripcion: 'Maletas de aluminio alemanas' },
  { id: 'fjallraven', nombre: 'Fjällräven', slug: 'fjallraven', descripcion: 'Mochilas y ropa outdoor sueca' },

  // === MARCAS DE NICHO / STREETWEAR LATINO ===
  { id: 'nicce', nombre: 'Nicce', slug: 'nicce', descripcion: 'Streetwear británico' },
  { id: 'ellesse', nombre: 'Ellesse', slug: 'ellesse', descripcion: 'Sportswear italiano retro' },
  { id: 'sergio-tacchini', nombre: 'Sergio Tacchini', slug: 'sergio-tacchini', descripcion: 'Sportswear italiano retro' },
  { id: 'diadora', nombre: 'Diadora', slug: 'diadora', descripcion: 'Calzado y ropa deportiva italiana' },
  { id: 'le-coq-sportif', nombre: 'Le Coq Sportif', slug: 'le-coq-sportif', descripcion: 'Sportswear francés' },
  { id: 'errea', nombre: 'Erreà', slug: 'errea', descripcion: 'Ropa deportiva italiana' },
  { id: 'lonsdale', nombre: 'Lonsdale', slug: 'lonsdale', descripcion: 'Ropa boxeo y streetwear' },
  { id: 'canterbury', nombre: 'Canterbury', slug: 'canterbury', descripcion: 'Ropa rugby y outdoor' },
  { id: 'castore', nombre: 'Castore', slug: 'castore', descripcion: 'Sportswear premium británico' },
  { id: 'athletic-club', nombre: 'Athletic Club', slug: 'athletic-club', descripcion: 'Moda deportiva independiente' },

  // === MODA SOSTENIBLE ===
  { id: 'eileen-fisher', nombre: 'Eileen Fisher', slug: 'eileen-fisher', descripcion: 'Moda sostenible americana' },
  { id: 'tentree', nombre: 'Tentree', slug: 'tentree', descripcion: 'Ropa sustentable canadiense' },
  { id: 'allbirds', nombre: 'Allbirds', slug: 'allbirds', descripcion: 'Calzado sustentable de lana' },
  { id: 'veja', nombre: 'Veja', slug: 'veja', descripcion: 'Sneakers ecológicos franceses' },
  { id: 'thought', nombre: 'Thought Clothing', slug: 'thought', descripcion: 'Moda sostenible británica' },
  { id: 'prAna', nombre: 'prAna', slug: 'prana', descripcion: 'Ropa outdoor sustentable' },
  { id: 'pact', nombre: 'Pact', slug: 'pact', descripcion: 'Básicos orgánicos americanos' },
  { id: 'patagonia-organic', nombre: 'Patagonia Organic', slug: 'patagonia-organic', descripcion: 'Ropa algodón orgánico' },
  { id: 'people-tree', nombre: 'People Tree', slug: 'people-tree', descripcion: 'Moda justa y orgánica' },
  { id: 'know-the-origin', nombre: 'Know The Origin', slug: 'know-the-origin', descripcion: 'Moda de comercio justo' },

  // === DENIM ESPECIALIZADO ===
  { id: 'ag-jeans', nombre: 'AG Jeans', slug: 'ag-jeans', descripcion: 'Denim premium californiano' },
  { id: 'frame', nombre: 'Frame Denim', slug: 'frame', descripcion: 'Denim premium LA' },
  { id: 'citizens-of-humanity', nombre: 'Citizens of Humanity', slug: 'coh', descripcion: 'Denim premium Los Angeles' },
  { id: 'mother-denim', nombre: 'Mother Denim', slug: 'mother-denim', descripcion: 'Denim creativo californiano' },
  { id: 'paige', nombre: 'Paige', slug: 'paige', descripcion: 'Denim premium americano' },
  { id: 'joe-s-jeans', nombre: "Joe's Jeans", slug: 'joes-jeans', descripcion: 'Denim premium LA' },
  { id: 'true-religion', nombre: 'True Religion', slug: 'true-religion', descripcion: 'Denim premium con puntada característica' },
  { id: 'rock-republic', nombre: 'Rock & Republic', slug: 'rock-republic', descripcion: 'Denim fashion premium' },
  { id: 'rich-skinny', nombre: 'Rich & Skinny', slug: 'rich-skinny', descripcion: 'Denim slim premium' },
  { id: 'seven-for-all-mankind', nombre: '7 For All Mankind', slug: '7fam', descripcion: 'Denim premium icónico' },
  { id: 'rag-bone', nombre: 'Rag & Bone', slug: 'rag-bone', descripcion: 'Moda americana-británica premium' },
  { id: 'j-brand', nombre: 'J Brand', slug: 'j-brand', descripcion: 'Denim premium americano' },
  { id: 'nudies', nombre: 'Nudie Jeans', slug: 'nudie', descripcion: 'Denim sueco orgánico' },
  { id: 'acne-jeans', nombre: 'Acne Studios Jeans', slug: 'acne-jeans', descripcion: 'Denim escandinavo de diseñador' },
  { id: 'apc-jeans', nombre: 'A.P.C. Denim', slug: 'apc-jeans', descripcion: 'Denim francés clásico' },
  { id: 'raleigh-denim', nombre: 'Raleigh Denim', slug: 'raleigh', descripcion: 'Denim artesanal americano' },

  // === MARCAS ADICIONALES POPULARES EN MÉXICO ===
  { id: 'sport-city', nombre: 'Sport City', slug: 'sport-city', descripcion: 'Tienda deportiva mexicana' },
  { id: 'go-sport', nombre: 'Go Sport', slug: 'go-sport', descripcion: 'Tienda deportiva francesa en México' },
  { id: 'decathlon', nombre: 'Decathlon', slug: 'decathlon', descripcion: 'Tienda deportiva francesa' },
  { id: 'nike-mx', nombre: 'Nike México', slug: 'nike-mx', descripcion: 'Nike oficial en México' },
  { id: 'adidas-mx', nombre: 'Adidas México', slug: 'adidas-mx', descripcion: 'Adidas oficial en México' },
  { id: 'puma-mx', nombre: 'Puma México', slug: 'puma-mx', descripcion: 'Puma oficial en México' },
  { id: 'palace-hierro', nombre: 'Palacio de Hierro', slug: 'palacio-hierro', descripcion: 'Departamental premium mexicana' },
  { id: 'fashion-nova', nombre: 'Fashion Nova', slug: 'fashion-nova', descripcion: 'Moda rápida online popular' },
  { id: 'boohoo', nombre: 'Boohoo', slug: 'boohoo', descripcion: 'Moda online británica accesible' },
  { id: 'pretty-little-thing', nombre: 'PrettyLittleThing', slug: 'plt', descripcion: 'Moda femenina online accesible' },
  { id: 'nasty-gal', nombre: 'Nasty Gal', slug: 'nasty-gal', descripcion: 'Moda femenina atrevida' },
  { id: 'missguided', nombre: 'Missguided', slug: 'missguided', descripcion: 'Moda joven femenina online' },
  { id: 'asos', nombre: 'ASOS', slug: 'asos', descripcion: 'Marketplace de moda online' },
  { id: 'urban-outfitters', nombre: 'Urban Outfitters', slug: 'urban-outfitters', descripcion: 'Moda alternativa americana' },
  { id: 'topshop', nombre: 'Topshop', slug: 'topshop', descripcion: 'Moda femenina británica' },
  { id: 'river-island', nombre: 'River Island', slug: 'river-island', descripcion: 'Moda accesible británica' },
  { id: 'next', nombre: 'Next', slug: 'next', descripcion: 'Moda familiar británica' },
  { id: 'marks-spencer', nombre: 'Marks & Spencer', slug: 'marks-spencer', descripcion: 'Moda y básicos británicos' },
  { id: 'john-lewis', nombre: 'John Lewis', slug: 'john-lewis', descripcion: 'Departamental británico premium' },
  { id: 'farfetch', nombre: 'Farfetch', slug: 'farfetch', descripcion: 'Marketplace de moda de lujo' },
  { id: 'net-a-porter', nombre: 'Net-a-Porter', slug: 'net-a-porter', descripcion: 'E-commerce de lujo femenino' },
  { id: 'mr-porter', nombre: 'Mr Porter', slug: 'mr-porter', descripcion: 'E-commerce de lujo masculino' },
  { id: 'ssense', nombre: 'SSENSE', slug: 'ssense', descripcion: 'E-commerce de lujo canadiense' },
  { id: 'matches-fashion', nombre: 'Matches Fashion', slug: 'matches', descripcion: 'E-commerce de lujo multimarco' },
]